// Initial Default Dataset for EduFee Android App
export const INITIAL_SCHOOL = {
  name: "Apex International Academy",
  tagline: "Excellence in Knowledge, Character & Leadership",
  phone: "+1 (555) 349-8821",
  email: "admin@apexschool.edu",
  address: "742 Knowledge Boulevard, Silicon Valley",
  currency: "$",
  feeDueDay: 10,
  academicYear: "2026 - 2027",
  logoEmoji: "🏫",
  adminName: "Principal Sarah Jenkins",
  bankDetails: "Chase Bank | A/C: 9812-4410-23 | Zelle: fee@apexschool.edu"
};

export const INITIAL_BATCHES = [
  {
    id: "batch-1",
    name: "Grade 10 - Science Elite",
    grade: "10",
    section: "A",
    incharge: "Dr. Arthur Sterling",
    defaultFee: 180,
    session: "2026-2027",
    color: "#4f46e5"
  },
  {
    id: "batch-2",
    name: "Grade 9 - Standard",
    grade: "9",
    section: "B",
    incharge: "Ms. Helena Clark",
    defaultFee: 150,
    session: "2026-2027",
    color: "#06b6d4"
  },
  {
    id: "batch-3",
    name: "Primary - Grade 5 Stars",
    grade: "5",
    section: "Gold",
    incharge: "Mr. David Miller",
    defaultFee: 120,
    session: "2026-2027",
    color: "#10b981"
  }
];

export const INITIAL_STUDENTS = [
  {
    id: "std-1",
    rollNo: "SCI-101",
    name: "Alexander Wright",
    batchId: "batch-1",
    parentName: "Thomas Wright",
    parentPhone: "+15552345678",
    monthlyFee: 180,
    discount: 0,
    admissionDate: "2026-08-10",
    gender: "Male",
    status: "active"
  },
  {
    id: "std-2",
    rollNo: "SCI-102",
    name: "Sophia Martinez",
    batchId: "batch-1",
    parentName: "Elena Martinez",
    parentPhone: "+15552345679",
    monthlyFee: 180,
    discount: 30, // Merit concession
    admissionDate: "2026-08-11",
    gender: "Female",
    status: "active"
  },
  {
    id: "std-3",
    rollNo: "SCI-103",
    name: "Lucas Chen",
    batchId: "batch-1",
    parentName: "David Chen",
    parentPhone: "+15552345680",
    monthlyFee: 180,
    discount: 0,
    admissionDate: "2026-08-15",
    gender: "Male",
    status: "active"
  },
  {
    id: "std-4",
    rollNo: "G9-201",
    name: "Emma Watson",
    batchId: "batch-2",
    parentName: "Arthur Watson",
    parentPhone: "+15552345681",
    monthlyFee: 150,
    discount: 0,
    admissionDate: "2026-08-20",
    gender: "Female",
    status: "active"
  },
  {
    id: "std-5",
    rollNo: "G9-202",
    name: "Liam Johnson",
    batchId: "batch-2",
    parentName: "Grace Johnson",
    parentPhone: "+15552345682",
    monthlyFee: 150,
    discount: 0,
    admissionDate: "2026-08-22",
    gender: "Male",
    status: "active"
  },
  {
    id: "std-6",
    rollNo: "G9-203",
    name: "Olivia Brown",
    batchId: "batch-2",
    parentName: "Robert Brown",
    parentPhone: "+15552345683",
    monthlyFee: 150,
    discount: 20,
    admissionDate: "2026-08-25",
    gender: "Female",
    status: "active"
  },
  {
    id: "std-7",
    rollNo: "PRI-501",
    name: "Noah Garcia",
    batchId: "batch-3",
    parentName: "Maria Garcia",
    parentPhone: "+15552345684",
    monthlyFee: 120,
    discount: 0,
    admissionDate: "2026-09-01",
    gender: "Male",
    status: "active"
  },
  {
    id: "std-8",
    rollNo: "PRI-502",
    name: "Ava Wilson",
    batchId: "batch-3",
    parentName: "James Wilson",
    parentPhone: "+15552345685",
    monthlyFee: 120,
    discount: 0,
    admissionDate: "2026-09-02",
    gender: "Female",
    status: "active"
  }
];

export const INITIAL_FEE_RECORDS = [
  // Current month (October 2026)
  {
    id: "fee-std-1-2026-10",
    studentId: "std-1",
    month: 10,
    year: 2026,
    baseAmount: 180,
    discount: 0,
    fine: 0,
    finalAmount: 180,
    paidAmount: 180,
    status: "PAID",
    paymentDate: "2026-10-01",
    paymentMode: "Online Banking",
    receiptNo: "RCP-2026-1001",
    remarks: "Paid in full via online transfer"
  },
  {
    id: "fee-std-2-2026-10",
    studentId: "std-2",
    month: 10,
    year: 2026,
    baseAmount: 180,
    discount: 30,
    fine: 0,
    finalAmount: 150,
    paidAmount: 150,
    status: "PAID",
    paymentDate: "2026-10-02",
    paymentMode: "Cash",
    receiptNo: "RCP-2026-1002",
    remarks: "Concession applied"
  },
  {
    id: "fee-std-3-2026-10",
    studentId: "std-3",
    month: 10,
    year: 2026,
    baseAmount: 180,
    discount: 0,
    fine: 0,
    finalAmount: 180,
    paidAmount: 100,
    status: "PARTIAL",
    paymentDate: "2026-10-04",
    paymentMode: "Cash",
    receiptNo: "RCP-2026-1003",
    remarks: "First installment. Remaining $80 due next week"
  },
  {
    id: "fee-std-4-2026-10",
    studentId: "std-4",
    month: 10,
    year: 2026,
    baseAmount: 150,
    discount: 0,
    fine: 0,
    finalAmount: 150,
    paidAmount: 150,
    status: "PAID",
    paymentDate: "2026-10-03",
    paymentMode: "Card / POS",
    receiptNo: "RCP-2026-1004",
    remarks: "Paid at school reception"
  },
  {
    id: "fee-std-5-2026-10",
    studentId: "std-5",
    month: 10,
    year: 2026,
    baseAmount: 150,
    discount: 0,
    fine: 10,
    finalAmount: 160,
    paidAmount: 0,
    status: "UNPAID",
    paymentDate: null,
    paymentMode: null,
    receiptNo: null,
    remarks: "Monthly fee pending"
  },
  {
    id: "fee-std-6-2026-10",
    studentId: "std-6",
    month: 10,
    year: 2026,
    baseAmount: 150,
    discount: 20,
    fine: 0,
    finalAmount: 130,
    paidAmount: 0,
    status: "UNPAID",
    paymentDate: null,
    paymentMode: null,
    receiptNo: null,
    remarks: "Sibling discount"
  },
  {
    id: "fee-std-7-2026-10",
    studentId: "std-7",
    month: 10,
    year: 2026,
    baseAmount: 120,
    discount: 0,
    fine: 0,
    finalAmount: 120,
    paidAmount: 120,
    status: "PAID",
    paymentDate: "2026-10-01",
    paymentMode: "Online Transfer",
    receiptNo: "RCP-2026-1005",
    remarks: "Paid on time"
  },
  {
    id: "fee-std-8-2026-10",
    studentId: "std-8",
    month: 10,
    year: 2026,
    baseAmount: 120,
    discount: 0,
    fine: 0,
    finalAmount: 120,
    paidAmount: 0,
    status: "UNPAID",
    paymentDate: null,
    paymentMode: null,
    receiptNo: null,
    remarks: "Awaiting parent payment"
  },

  // Past month (September 2026) records for historical trend
  {
    id: "fee-std-1-2026-9",
    studentId: "std-1",
    month: 9,
    year: 2026,
    baseAmount: 180,
    discount: 0,
    fine: 0,
    finalAmount: 180,
    paidAmount: 180,
    status: "PAID",
    paymentDate: "2026-09-03",
    paymentMode: "Online Banking",
    receiptNo: "RCP-2026-0901",
    remarks: "Clear"
  },
  {
    id: "fee-std-2-2026-9",
    studentId: "std-2",
    month: 9,
    year: 2026,
    baseAmount: 180,
    discount: 30,
    fine: 0,
    finalAmount: 150,
    paidAmount: 150,
    status: "PAID",
    paymentDate: "2026-09-05",
    paymentMode: "Cash",
    receiptNo: "RCP-2026-0902",
    remarks: "Clear"
  },
  {
    id: "fee-std-5-2026-9",
    studentId: "std-5",
    month: 9,
    year: 2026,
    baseAmount: 150,
    discount: 0,
    fine: 0,
    finalAmount: 150,
    paidAmount: 150,
    status: "PAID",
    paymentDate: "2026-09-10",
    paymentMode: "Cash",
    receiptNo: "RCP-2026-0905",
    remarks: "Clear"
  }
];

export const MONTHS = [
  { index: 1, name: "January", short: "Jan" },
  { index: 2, name: "February", short: "Feb" },
  { index: 3, name: "March", short: "Mar" },
  { index: 4, name: "April", short: "Apr" },
  { index: 5, name: "May", short: "May" },
  { index: 6, name: "June", short: "Jun" },
  { index: 7, name: "July", short: "Jul" },
  { index: 8, name: "August", short: "Aug" },
  { index: 9, name: "September", short: "Sep" },
  { index: 10, name: "October", short: "Oct" },
  { index: 11, name: "November", short: "Nov" },
  { index: 12, name: "December", short: "Dec" }
];
